/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
 * the MIT License. See LICENSE in the project root for license information.
 * <autogenerated> This file was generated using AutoRest. </autogenerated>
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the DeleteTopicNameRequest class.
 * @constructor
 * Request to delete a topic name
 * @member {string} publisherType Gets or sets publisher type. Possible values
 * include: 'User', 'App'
 * 
 */
function DeleteTopicNameRequest() {
}

/**
 * Defines the metadata of DeleteTopicNameRequest
 *
 * @returns {object} metadata of DeleteTopicNameRequest
 *
 */
DeleteTopicNameRequest.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'DeleteTopicNameRequest',
    type: {
      name: 'Composite',
      className: 'DeleteTopicNameRequest',
      modelProperties: {
        publisherType: {
          required: true,
          serializedName: 'publisherType',
          type: {
            name: 'Enum',
            allowedValues: [ 'User', 'App' ]
          }
        }
      }
    }
  };
};

module.exports = DeleteTopicNameRequest;
