/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
 * the MIT License. See LICENSE in the project root for license information.
 * <autogenerated> This file was generated using AutoRest. </autogenerated>
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the PostSessionRequest class.
 * @constructor
 * Request to post (create) session
 * @member {string} instanceId Gets or sets instance id -- Unique installation
 * id of the app
 * 
 * @member {string} userHandle Gets or sets user handle
 * 
 */
function PostSessionRequest() {
}

/**
 * Defines the metadata of PostSessionRequest
 *
 * @returns {object} metadata of PostSessionRequest
 *
 */
PostSessionRequest.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'PostSessionRequest',
    type: {
      name: 'Composite',
      className: 'PostSessionRequest',
      modelProperties: {
        instanceId: {
          required: true,
          serializedName: 'instanceId',
          type: {
            name: 'String'
          }
        },
        userHandle: {
          required: true,
          serializedName: 'userHandle',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = PostSessionRequest;
