/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
 * the MIT License. See LICENSE in the project root for license information.
 * This file was generated using AutoRest.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the PostSessionResponse class.
 * @constructor
 * Response from post (create) session
 * @member {string} userHandle Gets or sets user handle
 * 
 * @member {string} sessionToken Gets or sets session token generated by our
 * server.
 * The client saves the session token and sends it with every
 * request
 * 
 */
function PostSessionResponse() {
}

/**
 * Defines the metadata of PostSessionResponse
 *
 * @returns {object} metadata of PostSessionResponse
 *
 */
PostSessionResponse.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'PostSessionResponse',
    type: {
      name: 'Composite',
      className: 'PostSessionResponse',
      modelProperties: {
        userHandle: {
          required: true,
          serializedName: 'userHandle',
          type: {
            name: 'String'
          }
        },
        sessionToken: {
          required: true,
          serializedName: 'sessionToken',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = PostSessionResponse;
