/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
 * the MIT License. See LICENSE in the project root for license information.
 * <autogenerated> This file was generated using AutoRest. </autogenerated>
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the PostFollowingUserRequest class.
 * @constructor
 * Request to follow a user
 * @member {string} userHandle Gets or sets user handle
 * 
 */
function PostFollowingUserRequest() {
}

/**
 * Defines the metadata of PostFollowingUserRequest
 *
 * @returns {object} metadata of PostFollowingUserRequest
 *
 */
PostFollowingUserRequest.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'PostFollowingUserRequest',
    type: {
      name: 'Composite',
      className: 'PostFollowingUserRequest',
      modelProperties: {
        userHandle: {
          required: true,
          serializedName: 'userHandle',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = PostFollowingUserRequest;
