/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
 * the MIT License. See LICENSE in the project root for license information.
 * <autogenerated> This file was generated using AutoRest. </autogenerated>
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the PostTopicNameRequest class.
 * @constructor
 * Post topic name request
 * @member {string} publisherType Gets or sets publisher type. Possible values
 * include: 'User', 'App'
 * 
 * @member {string} topicName Gets or sets topic name
 * 
 * @member {string} topicHandle Gets or sets topic handle
 * 
 */
function PostTopicNameRequest() {
}

/**
 * Defines the metadata of PostTopicNameRequest
 *
 * @returns {object} metadata of PostTopicNameRequest
 *
 */
PostTopicNameRequest.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'PostTopicNameRequest',
    type: {
      name: 'Composite',
      className: 'PostTopicNameRequest',
      modelProperties: {
        publisherType: {
          required: true,
          serializedName: 'publisherType',
          type: {
            name: 'Enum',
            allowedValues: [ 'User', 'App' ]
          }
        },
        topicName: {
          required: true,
          serializedName: 'topicName',
          type: {
            name: 'String'
          }
        },
        topicHandle: {
          required: true,
          serializedName: 'topicHandle',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = PostTopicNameRequest;
