/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
 * the MIT License. See LICENSE in the project root for license information.
 * <autogenerated> This file was generated using AutoRest. </autogenerated>
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the PostReportRequest class.
 * @constructor
 * Request to post (create) a report for content
 * @member {string} reason Gets or sets report reason. Possible values
 * include: 'ThreatsCyberbullyingHarassment',
 * 'ChildEndangermentExploitation', 'OffensiveContent',
 * 'VirusSpywareMalware', 'ContentInfringement', 'Other', 'None'
 * 
 */
function PostReportRequest() {
}

/**
 * Defines the metadata of PostReportRequest
 *
 * @returns {object} metadata of PostReportRequest
 *
 */
PostReportRequest.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'PostReportRequest',
    type: {
      name: 'Composite',
      className: 'PostReportRequest',
      modelProperties: {
        reason: {
          required: true,
          serializedName: 'reason',
          type: {
            name: 'Enum',
            allowedValues: [ 'ThreatsCyberbullyingHarassment', 'ChildEndangermentExploitation', 'OffensiveContent', 'VirusSpywareMalware', 'ContentInfringement', 'Other', 'None' ]
          }
        }
      }
    }
  };
};

module.exports = PostReportRequest;
