/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
 * the MIT License. See LICENSE in the project root for license information.
 * <autogenerated> This file was generated using AutoRest. </autogenerated>
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the PostLinkedAccountRequest class.
 * @constructor
 * Request to post (create) linked account
 * @member {string} sessionToken Gets or sets a session token.
 * 
 */
function PostLinkedAccountRequest() {
}

/**
 * Defines the metadata of PostLinkedAccountRequest
 *
 * @returns {object} metadata of PostLinkedAccountRequest
 *
 */
PostLinkedAccountRequest.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'PostLinkedAccountRequest',
    type: {
      name: 'Composite',
      className: 'PostLinkedAccountRequest',
      modelProperties: {
        sessionToken: {
          required: true,
          serializedName: 'sessionToken',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = PostLinkedAccountRequest;
