/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
 * the MIT License. See LICENSE in the project root for license information.
 * <autogenerated> This file was generated using AutoRest. </autogenerated>
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the PutPushRegistrationRequest class.
 * @constructor
 * Request to put push registration (register or update)
 * @member {date} lastUpdatedTime Gets or sets last updated time from the OS
 * This is used to expire out registrations that have not been
 * updated every 30 days.
 * 
 * @member {string} language Gets or sets language of the user
 * 
 */
function PutPushRegistrationRequest() {
}

/**
 * Defines the metadata of PutPushRegistrationRequest
 *
 * @returns {object} metadata of PutPushRegistrationRequest
 *
 */
PutPushRegistrationRequest.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'PutPushRegistrationRequest',
    type: {
      name: 'Composite',
      className: 'PutPushRegistrationRequest',
      modelProperties: {
        lastUpdatedTime: {
          required: true,
          serializedName: 'lastUpdatedTime',
          type: {
            name: 'DateTime'
          }
        },
        language: {
          required: true,
          serializedName: 'language',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = PutPushRegistrationRequest;
